### ISSUE TITLE
magick/api.h not found during make

### ISSUE THREAD

**Issue by neelsbrink** [msmolens/smoke-simulation#1]
Hi, when I try to make the simulation, I get a fatal error that magick/api.h is not found. I have tried various versions of ImageMagick.
I am working on Ubuntu.
thanks
Neels

**Comment by msmolens** [comment]
This project is from 2003, so it's not surprising that it doesn't compile out of the box on modern systems! I'll archive the repository to make this clear.

Regardless, try installing the `graphicsmagick-libmagick-dev-compat` package so that the Makefile finds `Magick++-config`.
